# Generated by Django 2.0.5 on 2018-10-27 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_private_key', models.CharField(blank=True, max_length=100, null=True)),
                ('wallet_account', models.CharField(blank=True, max_length=100, null=True)),
                ('rsa_private_key', models.CharField(blank=True, max_length=1000, null=True)),
                ('rsa_public_key', models.CharField(blank=True, max_length=1000, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='users_related', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
